# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: app start
        with:
          start:  |
                cd src/client
                npm ci
                npm run start & npx wait-on http://localhost:1917
        env:
          CI: true
      
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
         working-directory: src/cypress
         start: |
              cd ../client
              npm run start
              cd ../cypress
              npm run tests
        env:
          CI: true
          

